apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: '../versions.gradle'

android {
  kotlinOptions { jvmTarget = "21" }
  compileOptions {
    coreLibraryDesugaringEnabled true
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
  }

  compileSdkVersion versions.compileSdk

  defaultConfig {
    minSdkVersion versions.minSdk
    compileSdkVersion versions.compileSdk

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  namespace 'com.michaldrabik.ui_navigation'
  lint {
    targetSdk 36
  }
  testOptions {
    targetSdk 36
  }
}

dependencies {
  api libs.bundles.android.navigation
  coreLibraryDesugaring libs.android.desugar
}
